# Generated by Django 5.2.7 on 2026-01-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('base_currency', models.CharField(default='KZT', max_length=3)),
                ('source', models.CharField(default='default_api', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
