# Generated by Django 5.2.10 on 2026-01-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс валюты', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='base_currency',
            field=models.CharField(default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='source',
            field=models.CharField(default='exchangerate-api', max_length=50),
        ),
    ]
